### ISSUE TITLE
Remove unused validator functions

### ISSUE THREAD

**Issue by malimccalla** [jaakmusic/jaak.js#48]
We need to revise the use of validator functions used within `playback-utils`. We should be able to safely remove `isValidAccount` and `isValidAddress` all together.

It may also be worth revisiting the regular expressions used to validate and see if there is any room for improvement/stricter testing. Validators like `isValidPrivateKey` can even be removed in favour of delegating the logic of the validation to the [`ethereumjs-util`](https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/index.md#isvalidprivate) dependency

**Comment by MrTibbles** [comment]
@lmars i am hesitant to adopt the `ec-key` library due to this comment:

> PLEASE NOTE: The P-256K curve name (crv parameter) used when serializing a key using the secp384k1 curve is not standard, and NOT interoperable with other systems.

Would you agree that migrating to that library is not worth the _risk_?

**Comment by lmars** [comment]
@MrTibbles I think `secp384k1` is a typo (there is no such curve).

They are re-iterating that using the `secp256k1` curve with JSON Web Tokens is non standard, but we've already decided to do that (this is whey we use Blockstack's jsontokens-js lib rather than the more popular Auth0 jsonwebtoken lib).

**Comment by MrTibbles** [comment]
Oh right, thanks.

**Comment by malimccalla** [comment]
Closing this as none of the current validators are unused
